security:
    access_control:
        -
            path: ^/login$
            roles:
                - IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/self/register$
            roles:
                - IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/resetting$
            roles:
                - IS_AUTHENTICATED_ANONYMOUSLY
