<?php

namespace PressingBundle\Repository;

/**
 * ArticleIntervenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleIntervenantRepository extends \Doctrine\ORM\EntityRepository
{
}
