<?php

namespace PressingBundle\Repository;

/**
 * EntreFinanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntreFinanceRepository extends \Doctrine\ORM\EntityRepository
{
}
